In [3]:
import pandas as pd
import numpy as np

datam= [1,2,39,67,90]

In [4]:
pd.DataFrame(datam, columns=['column_name'])

column_name
0            1
1            2
2           39
3           67
4           90

In [6]:
m = np.arange(1,10).reshape(3,3)
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
pd.DataFrame(m, columns=['var1','var2', 'var3'])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [8]:
df = pd.DataFrame(m, columns=['var1','var2', 'var3'])
df

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [9]:
df.head(2)

var1  var2  var3
0     1     2     3
1     4     5     6

In [10]:
df.tail(1)

var1  var2  var3
2     7     8     9

In [11]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [12]:
for i in df.columns:
    print(i)

var1
var2
var3


In [14]:
df.columns = ['new1', 'new2', 'new3']
df

new1  new2  new3
0     1     2     3
1     4     5     6
2     7     8     9

In [15]:
df.shape

(3, 3)

In [16]:
df.ndim

2

In [17]:
df.size

9

In [18]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
type(df.values)

numpy.ndarray

In [20]:
s1 =np.random.randint(10, size = 5)
s2 =np.random.randint(10, size = 5)
s3 =np.random.randint(10, size = 5)

In [21]:
s1

array([3, 3, 6, 5, 8])

In [22]:
s2

array([2, 8, 6, 9, 0])

In [23]:
s3

array([2, 0, 6, 6, 9])

In [26]:
myDict = {'var1':s1, 'var2':s2, 'var3':s3}
df1=pd.DataFrame(myDict)
df1

var1  var2  var3
0     3     2     2
1     3     8     0
2     6     6     6
3     5     9     6
4     8     0     9

In [27]:
pwd

'c:\\Users\\John\\Desktop\\Calrusway\\PYTHON\\Pandas'

In [ ]:
df3 = pd.read_csv('ornekcsv.csv')

In [28]:
df1[1:3]

var1  var2  var3
1     3     8     0
2     6     6     6

In [29]:
df1.index

RangeIndex(start=0, stop=5, step=1)

In [31]:
[i for i in df1.index]

[0, 1, 2, 3, 4]

In [34]:
df1.index = ['a', 'b', 'c', 'd', 'e']
df1

var1  var2  var3
a     3     2     2
b     3     8     0
c     6     6     6
d     5     9     6
e     8     0     9

In [35]:
df1['b': 'd']

var1  var2  var3
b     3     8     0
c     6     6     6
d     5     9     6

In [36]:
'var2' in df1

True

In [37]:
'joseph' in df1

False

In [38]:
from numpy.random import randn
np.random.seed(101)

In [39]:
df3 = pd.DataFrame(randn(5,4), index='A B C D E'.split(), columns='W X Y Z'.split())
# df3 = pd.DataFrame(randn(5,4), 'A B C D E'.split(), 'W X Y Z'.split())
# df3 = pd.DataFrame(index='A B C D E'.split(), columns='W X Y Z'.split(),data=randn(5,4))

In [41]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [42]:
df3['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [44]:
type(df3['W'])

pandas.core.series.Series

In [46]:
df3['W'].values

array([ 2.70684984,  0.65111795, -2.01816824,  0.18869531,  0.19079432])

In [47]:
df3['W'].ndim

1

In [48]:
df3[['W']]

W
A  2.706850
B  0.651118
C -2.018168
D  0.188695
E  0.190794

In [49]:
type(df3[['W']])

pandas.core.frame.DataFrame

In [52]:
istediimsutunlar = ['W', 'Z']

WZ_df = df3[istediimsutunlar]
WZ_df


W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [54]:
df3.W  # = df3['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [56]:
df3['A':'C']

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001

In [57]:
df3['C': 'C']

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001